sed -i 's/const \[statusFilter, setStatusFilter\] = useState('\''Todos'\'');/const [statusFilter, setStatusFilter] = useState('\''Todos'\'');\n  const [dateFilter, setDateFilter] = useState('\''Todos'\'');\n  const [sortConfig, setSortConfig] = useState<{ key: string, direction: '\''asc'\'' | '\''desc'\'' } | null>(null);/g' components/FinanceView.tsx

sed -i 's/const filteredLots = lots.filter(lot => {/const handleSort = (key: string) => {\n    let direction: '\''asc'\'' | '\''desc'\'' = '\''asc'\'';\n    if (sortConfig \&\& sortConfig.key === key \&\& sortConfig.direction === '\''asc'\'') {\n      direction = '\''desc'\'';\n    }\n    setSortConfig({ key, direction });\n  };\n\n  const filteredLots = lots.filter(lot => {\n    const lotProps = proposals.filter(p => p.lote_id === lot.id);/g' components/FinanceView.tsx

sed -i 's/const matchesSearch = lot.codigo.toLowerCase().includes(searchTerm.toLowerCase());/const matchesSearch = \n      lot.codigo.toLowerCase().includes(searchTerm.toLowerCase()) ||\n      lotProps.some(p => \n        p.corretor.toLowerCase().includes(searchTerm.toLowerCase()) || \n        (p.contrato \&\& p.contrato.toLowerCase().includes(searchTerm.toLowerCase()))\n      );/g' components/FinanceView.tsx

sed -i 's/return matchesSearch && matchesStatus;/let matchesDate = true;\n    if (dateFilter !== '\''Todos'\'' \&\& lot.vencimento) {\n      const today = new Date();\n      let lotDate = new Date();\n      if (lot.vencimento !== '\''Hoje'\'') {\n        if (lot.vencimento.match(\/^\\d{4}-\\d{2}-\\d{2}$\/)) {\n          lotDate = new Date(lot.vencimento);\n        } else {\n          lotDate = new Date(0);\n        }\n      }\n      \n      if (!isNaN(lotDate.getTime())) {\n        if (dateFilter === '\''Últimos 7 dias'\'') {\n          const sevenDaysAgo = new Date();\n          sevenDaysAgo.setDate(today.getDate() - 7);\n          matchesDate = lotDate >= sevenDaysAgo \&\& lotDate <= today;\n        } else if (dateFilter === '\''Últimos 30 dias'\'') {\n          const thirtyDaysAgo = new Date();\n          thirtyDaysAgo.setDate(today.getDate() - 30);\n          matchesDate = lotDate >= thirtyDaysAgo \&\& lotDate <= today;\n        } else if (dateFilter === '\''Este mês'\'') {\n          matchesDate = lotDate.getMonth() === today.getMonth() \&\& lotDate.getFullYear() === today.getFullYear();\n        } else if (dateFilter === '\''Mês passado'\'') {\n          const lastMonth = new Date(today.getFullYear(), today.getMonth() - 1, 1);\n          matchesDate = lotDate.getMonth() === lastMonth.getMonth() \&\& lotDate.getFullYear() === lastMonth.getFullYear();\n        }\n      }\n    }\n\n    return matchesSearch \&\& matchesStatus \&\& matchesDate;/g' components/FinanceView.tsx

sed -i 's/});\n\n  const totals = {/});\n\n  const sortedLots = [...filteredLots].sort((a, b) => {\n    if (!sortConfig) return 0;\n    \n    let aValue: any = a[sortConfig.key as keyof PaymentLot];\n    let bValue: any = b[sortConfig.key as keyof PaymentLot];\n\n    if (sortConfig.key === '\''valorTotal'\'') {\n      aValue = Number(aValue);\n      bValue = Number(bValue);\n    } else if (sortConfig.key === '\''qtdPropostas'\'') {\n      aValue = Number(aValue);\n      bValue = Number(bValue);\n    } else if (sortConfig.key === '\''vencimento'\'') {\n      const getMs = (v: string) => {\n         if (v === '\''Hoje'\'') return new Date().getTime();\n         const d = new Date(v);\n         return isNaN(d.getTime()) ? 0 : d.getTime();\n      };\n      aValue = getMs(aValue as string);\n      bValue = getMs(bValue as string);\n    }\n\n    if (aValue < bValue) {\n      return sortConfig.direction === '\''asc'\'' ? -1 : 1;\n    }\n    if (aValue > bValue) {\n      return sortConfig.direction === '\''asc'\'' ? 1 : -1;\n    }\n    return 0;\n  });\n\n  const totals = {/g' components/FinanceView.tsx

